name: ci-cd-pipeline file notifcation-service
on: 
  push:
    branches: 
      - master
jobs:

  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Docker Setup Docker
        uses: crazy-max/ghaction-setup-docker@v2.2.0
      - name: docker authenticate with ecr repo
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 402338187344.dkr.ecr.us-east-2.amazonaws.com